project:
  type: website
  output-dir: docs
    
website:
  title: "ABerral"
  favicon: "images/favicon.png"
  page-footer:
    center: |
      [Contact Me](mailto:aberralgonzalez@gmail.com)
    left: |
      Made with [Quarto](https://quarto.org/)
    right: |
      © Copyright 2025 Alberto Berral-González. Except where otherwise noted, all text and images licensed CC-BY-NC 4.0.
    background: "#636363"
    
    
  search: 
    location: navbar
    type: overlay
  navbar:
    right:
      - href: https://aberral.github.io/
        text: Home
      - href: publications/publications.qmd
        text: Publications
      - href: posts/post.qmd
        text: Posts
      - href: galleries/index.qmd
        text: Gallery
      - href: resume/resume.qmd
        text: Resume
      - icon: github
        href: https://github.com/aberral
      - icon: linkedin
        href: https://www.linkedin.com/in/aberralgonzalez/
      - icon: envelope-fill
        href: mailto:///aberralgonzalez@gmail.com
format:
  html:
    theme: 
      light: minty
      dark: cyborg
    css: styles.css
    code-link: true
    code-fold: show
    # code-tools: true
    code-block-bg: "#FCF6F5"
    code-block-border-left: "#2BAE66"

editor: visual

